default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>

development:
  <<: *default
  database: savy_shop_development

test:
  <<: *default
  database: savy_shop_test

production:
  <<: *default
  database: savy_shop_production
